name: Jira Automation

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  update-jira:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    timeout-minutes: 5

    steps:
      - name: Check pull request information
        id: check-pr
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"
          if [ -z "${{ github.event.pull_request.title }}" ]; then
            echo "HAS_TITLE=false" >> $GITHUB_ENV
          else
            echo "HAS_TITLE=true" >> $GITHUB_ENV
          fi

      - name: Login to Jira
        id: login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Extract issue key (title + branch fallback)
        id: extract-key
        run: |
          ISSUE_KEY=""
          PR_TITLE="${{ github.event.pull_request.title }}"
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"

          echo "Checking PR title: $PR_TITLE"

          # Standard pattern
          ISSUE_KEY=$(echo "$PR_TITLE" | grep -o -E '[A-Z]+-[0-9]+' | head -n 1)

          # Fallback: handle "seg 5" type
          if [ -z "$ISSUE_KEY" ]; then
            SEG_NUM=$(echo "$PR_TITLE" | grep -o -E 'seg\s+[0-9]+' | sed -E 's/seg\s+([0-9]+)/\1/' | head -n 1)
            if [ -n "$SEG_NUM" ]; then
              ISSUE_KEY="SEG-$SEG_NUM"
            fi
          fi

          # Fallback to branch name if still empty
          if [ -z "$ISSUE_KEY" ]; then
            echo "No issue key found in title. Checking branch: $BRANCH_NAME"
            ISSUE_KEY=$(echo "$BRANCH_NAME" | grep -o -E '[A-Z]+-[0-9]+' | head -n 1)
            if [ -z "$ISSUE_KEY" ]; then
              SEG_NUM=$(echo "$BRANCH_NAME" | grep -o -E 'seg-?[0-9]+' | sed -E 's/seg-?([0-9]+).*/\1/' | head -n 1)
              if [ -n "$SEG_NUM" ]; then
                ISSUE_KEY="SEG-$SEG_NUM"
              fi
            fi
          fi

          if [ -n "$ISSUE_KEY" ]; then
            echo "Found issue key: $ISSUE_KEY"
            echo "ISSUE_KEY=$ISSUE_KEY" >> $GITHUB_ENV
            echo "::set-output name=issue_key::$ISSUE_KEY"
          else
            echo "No Jira issue key found"
            echo "ISSUE_KEY=" >> $GITHUB_ENV
            echo "::set-output name=issue_key::"
          fi

      - name: Check if issue key was found
        id: check-issue
        run: |
          if [ -n "${{ steps.extract-key.outputs.issue_key }}" ]; then
            echo "ISSUE_FOUND=true" >> $GITHUB_ENV
            echo "::notice::Final Jira issue key: ${{ steps.extract-key.outputs.issue_key }}"
          else
            echo "ISSUE_FOUND=false" >> $GITHUB_ENV
            echo "::warning::No Jira issue key found in PR title or branch name"
          fi

      - name: Get available transitions
        id: get-transitions
        if: env.ISSUE_FOUND == 'true'
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.extract-key.outputs.issue_key }}
          list: true

      - name: Show available transitions
        if: env.ISSUE_FOUND == 'true'
        run: |
          echo "Available transitions for ${{ steps.extract-key.outputs.issue_key }}:"
          echo "${{ steps.get-transitions.outputs.transitions }}"

      - name: Move Jira issue to Done
        id: transition
        if: env.ISSUE_FOUND == 'true'
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.extract-key.outputs.issue_key }}
          transition: "31"

      - name: Verify transition success
        if: env.ISSUE_FOUND == 'true'
        run: |
          if [ "${{ steps.transition.outcome }}" == "success" ]; then
            echo "✅ Successfully moved ${{ steps.extract-key.outputs.issue_key }} to Done status"
          else
            echo "::error::Failed to transition ${{ steps.extract-key.outputs.issue_key }} to Done status"
            exit 1
          fi
